kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: fluent-bit
  namespace: builder
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
  annotations:
    deprecated.daemonset.template.generation: '10'
    meta.helm.sh/release-name: builder
    meta.helm.sh/release-namespace: builder
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      name: fluent-bit
      namespace: builder
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: fluent-bit
      annotations:
        kubesphere.io/restartedAt: '2022-04-20T07:36:56.601Z'
    spec:
      volumes:
        - name: varlibcontainers
          hostPath:
            path: /data/var/lib/docker/containers
            type: ''
        - name: config
          secret:
            secretName: fluent-bit-config
            defaultMode: 420
        - name: varlogs
          hostPath:
            path: /var/log
            type: ''
        - name: systemd
          hostPath:
            path: /var/log/journal
            type: ''
        - name: positions
          emptyDir: {}
      containers:
        - name: fluent-bit
          image: 'kubesphere/fluent-bit:v1.6.9'
          ports:
            - name: metrics
              containerPort: 2020
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources: {}
          volumeMounts:
            - name: varlibcontainers
              readOnly: true
              mountPath: /data/var/lib/docker/containers
            - name: config
              readOnly: true
              mountPath: /fluent-bit/config
            - name: varlogs
              readOnly: true
              mountPath: /var/log/
            - name: systemd
              readOnly: true
              mountPath: /var/log/journal
            - name: positions
              mountPath: /fluent-bit/tail
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: fluentbitds
      serviceAccount: fluentbitds
      securityContext: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/edge
                    operator: DoesNotExist
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
