kind: Service
apiVersion: v1
metadata:
  name: faas
  namespace: lowcode
  labels:
    app: faas
  annotations:
    kubesphere.io/creator: weitao
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32370
  selector:
    app: faas
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
