apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qxp-faas
rules:
  - apiGroups:
      - core.openfunction.io
    resources:
      - functions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
